/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogArticle {
  'title' : string,
  'body' : string,
  'summary' : string,
  'category' : string,
}
export interface CommunityPost { 'content' : string, 'author' : string }
export interface CoreValue { 'title' : string, 'description' : string }
export interface CropSnapshot {
  'soilMoisture' : bigint,
  'temperature' : bigint,
  'name' : string,
  'expectedHarvest' : string,
  'variety' : string,
  'health' : bigint,
}
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'ngo' : null } |
  { 'consumer' : null } |
  { 'farmer' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBlogArticle' : ActorMethod<[BlogArticle], undefined>,
  'addCommunityPost' : ActorMethod<[string], undefined>,
  'addCropSnapshot' : ActorMethod<[CropSnapshot], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'getAllArticles' : ActorMethod<[], Array<BlogArticle>>,
  'getAllPosts' : ActorMethod<[], Array<CommunityPost>>,
  'getArticlesByCategory' : ActorMethod<[string], Array<BlogArticle>>,
  'getCallerCrops' : ActorMethod<[], Array<CropSnapshot>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCoreValues' : ActorMethod<[], Array<CoreValue>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];