/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogArticle = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'summary' : IDL.Text,
  'category' : IDL.Text,
});
export const CropSnapshot = IDL.Record({
  'soilMoisture' : IDL.Nat,
  'temperature' : IDL.Nat,
  'name' : IDL.Text,
  'expectedHarvest' : IDL.Text,
  'variety' : IDL.Text,
  'health' : IDL.Nat,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CommunityPost = IDL.Record({
  'content' : IDL.Text,
  'author' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'ngo' : IDL.Null,
  'consumer' : IDL.Null,
  'farmer' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const CoreValue = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBlogArticle' : IDL.Func([BlogArticle], [], []),
  'addCommunityPost' : IDL.Func([IDL.Text], [], []),
  'addCropSnapshot' : IDL.Func([CropSnapshot], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(BlogArticle)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
  'getArticlesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(BlogArticle)],
      ['query'],
    ),
  'getCallerCrops' : IDL.Func([], [IDL.Vec(CropSnapshot)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getCoreValues' : IDL.Func([], [IDL.Vec(CoreValue)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogArticle = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'summary' : IDL.Text,
    'category' : IDL.Text,
  });
  const CropSnapshot = IDL.Record({
    'soilMoisture' : IDL.Nat,
    'temperature' : IDL.Nat,
    'name' : IDL.Text,
    'expectedHarvest' : IDL.Text,
    'variety' : IDL.Text,
    'health' : IDL.Nat,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CommunityPost = IDL.Record({
    'content' : IDL.Text,
    'author' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'ngo' : IDL.Null,
    'consumer' : IDL.Null,
    'farmer' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const CoreValue = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBlogArticle' : IDL.Func([BlogArticle], [], []),
    'addCommunityPost' : IDL.Func([IDL.Text], [], []),
    'addCropSnapshot' : IDL.Func([CropSnapshot], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(BlogArticle)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(CommunityPost)], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(BlogArticle)],
        ['query'],
      ),
    'getCallerCrops' : IDL.Func([], [IDL.Vec(CropSnapshot)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getCoreValues' : IDL.Func([], [IDL.Vec(CoreValue)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };